laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('produto/{produto_slug}', 'HomeController@show')->name('produto');
    Route::post('contato', 'ContatoController@post')->name('contato');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::get('produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
		]);
		Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
		Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Produto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use App\Helpers\Tools;
use Carbon\Carbon;

class Produto extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'produtos';

    protected $guarded = ['id'];

    protected $dates = ['vendido_em'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function scopeCategoria($query, $categoria_id)
    {
        return $query->where('produtos_categoria_id', $categoria_id);
    }

    public function categoria()
    {
        return $this->belongsTo('App\Models\ProdutoCategoria', 'produtos_categoria_id');
    }

    public function imagens()
    {
        return $this->hasMany('App\Models\ProdutoImagem', 'produto_id')->ordenados();
    }

    public static function upload_capa()
    {
        return CropImage::make('capa', [
            [
                'width'       => 405,
                'height'      => 240,
                'transparent' => true,
                'path'        => 'assets/img/produtos/'
            ],
            [
                'width'       => 810,
                'height'      => 480,
                'transparent' => true,
                'path'        => 'assets/img/produtos/ampliacao/'
            ]
        ]);
    }

    public function getValorFormatadoAttribute()
    {
        if ($this->valor_desconto <= 0) {
            return Tools::formataValor($this->valor);
        }

        return '<span>de: '.Tools::formataValor($this->valor).' |</span> por: '.Tools::formataValor($this->valor_desconto);
    }

    public function getValorRealAttribute()
    {
        return $this->valor_desconto > 0 ? $this->valor_desconto : $this->valor;
    }

    public function getValorRealFormatadoAttribute()
    {
        $valor = $this->valor_desconto > 0 ? $this->valor_desconto : $this->valor;

        return Tools::formataValor($valor);
    }

    public function getDataDeExpiracaoAttribute()
    {
        return $this->vendido_em->addDays(10);
    }

    public function getOcultoAttribute()
    {
        if (! $this->vendido || ! $this->vendido_em) {
            return false;
        }

        return $this->data_de_expiracao->lt(Carbon::now()->startOfDay());
    }
}

laravel/resources/views/frontend/home.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="filtros">
        <div class="center">
            <div class="filtro">
                <span>produto:</span>
                <select name="categoria">
                    <option value="">TODOS</option>
                    @foreach($categorias as $categoria)
                    <option value="{{ $categoria->slug }}" @if(request('categoria') == $categoria->slug) selected @endif>{{ mb_strtoupper($categoria->titulo) }}</option>
                    @endforeach
                </select>
            </div>

            <div class="filtro">
                <span>ordenar por:</span>
                <select name="ordem">
                    <option value="relevancia" @if(request('ordem') == 'relevancia') selected @endif>RELEVÂNCIA</option>
                    <option value="valor-asc" @if(request('ordem') == 'valor-asc') selected @endif>MENOR PREÇO</option>
                    <option value="valor-desc" @if(request('ordem') == 'valor-desc') selected @endif>MAIOR PREÇO</option>
                    <option value="desconto" @if(request('ordem') == 'desconto') selected @endif>% OFF</option>
                </select>
            </div>
        </div>
    </div>

    <div class="produtos">
        <div class="center">
            @if(! count($produtos))
            <div class="nenhum">Nenhum produto encontrado.</div>
            @else
            @foreach($produtos as $produto)
                <a href="{{ route('produto', $produto->slug) }}">
                    <img src="{{ asset('assets/img/produtos/'.$produto->capa) }}" alt="">
                    <h2>{{ $produto->titulo }}</h2>
                    <p>{!! $produto->valor_formatado !!}</p>

                    @if($produto->vendido)
                    <div class="vendido">
                        <span>VENDIDO</span>
                    </div>
                    @endif

                    @if($produto->porcentagem_desconto)
                    <div class="desconto">
                        <span>{{ $produto->porcentagem_desconto }}</span>
                    </div>
                    @endif
                </a>
            @endforeach
            @endif
        </div>
    </div>

@endsection

laravel/resources/views/frontend/produto.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="produto">
        <div class="center">
            <div class="left">
                <div class="display">
                    <img src="{{ asset('assets/img/produtos/ampliacao/'.$produto->capa) }}" alt="">
                </div>

                @if(count($produto->imagens))
                <div class="thumbs">
                    <div class="active" data-image="{{ asset('assets/img/produtos/ampliacao/'.$produto->capa) }}">
                        <img src="{{ asset('assets/img/produtos/'.$produto->capa) }}" alt="">
                    </div>
                    @foreach($produto->imagens as $imagem)
                    <div data-image="{{ asset('assets/img/produtos/ampliacao/'.$imagem->imagem) }}">
                        <img src="{{ asset('assets/img/produtos/'.$imagem->imagem) }}" alt="">
                    </div>
                    @endforeach
                </div>
                @endif

                <h2>{{ $produto->titulo }}</h2>
                <p>{!! $produto->valor_formatado !!}</p>

                @if($produto->vendido)
                <div class="vendido">
                    <span>VENDIDO</span>
                </div>
                @endif

                @if($produto->porcentagem_desconto)
                <div class="desconto">
                    <span>{{ $produto->porcentagem_desconto }}</span>
                </div>
                @endif
            </div>

            <div class="right">
                <h2>{{ $produto->titulo }}</h2>
                <p>{!! $produto->descricao !!}</p>

                <hr>

                <p class="valor">{{ Tools::formataValor($produto->valor_real) }}</p>

                @if(! $produto->vendido)
                <p class="estoque">Peças disponíveis: {{ $produto->estoque }}</p>

                @if(session('enviado'))
                <div class="enviado">
                    <div>
                        <span>Mensagem enviada com sucesso.</span>
                        <span>A Érea agradece o contato.</span>
                    </div>
                </div>
                @else
                <form action="{{ route('contato') }}" method="POST">
                    {!! csrf_field() !!}
                    <input type="hidden" name="produto_id" value="{{ $produto->id }}">
                    <input type="text" name="nome" value="{{ old('nome') }}" placeholder="nome do comprador" required>
                    <input type="email" name="email" value="{{ old('email') }}" placeholder="e-mail" required>
                    <input type="text" name="telefone" value="{{ old('telefone') }}" placeholder="telefone">
                    <input type="text" name="mensagem" value="{{ old('mensagem') }}" placeholder="comentário/observação">
                    <input type="submit" value="&raquo; COMPRAR">

                    @if($errors->any())
                    <div class="erro">Preencha todos os campos corretamente</div>
                    @endif
                </form>
                @endif

                <p class="estoque">Ao enviar sua solicitação nossa equipe entrará em contato para finalizar a aquisição. Aguarde seu contato via e-mail ou telefone.</p>
                @else
                <p class="estoque">Produto indisponível</p>
                @endif
            </div>
        </div>

        <div class="center">
            <a href="{{ route('home') }}" class="btn-voltar">
                VOLTAR PARA A VITRINE
            </a>
        </div>
    </div>


@endsection